# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.logos_api import LogosApi


class TestLogosApi(unittest.TestCase):
    """LogosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LogosApi()

    def tearDown(self) -> None:
        pass

    def test_images_logos_get(self) -> None:
        """Test case for images_logos_get

        Fetch logos
        """
        pass

    def test_images_logos_logo_id_reset_post(self) -> None:
        """Test case for images_logos_logo_id_reset_post

        Reset logo annotation
        """
        pass

    def test_images_logos_search_get(self) -> None:
        """Test case for images_logos_search_get

        Search for logos
        """
        pass


if __name__ == '__main__':
    unittest.main()
