# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.insights_api import InsightsApi


class TestInsightsApi(unittest.TestCase):
    """InsightsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InsightsApi()

    def tearDown(self) -> None:
        pass

    def test_insights_annotate_post(self) -> None:
        """Test case for insights_annotate_post

        Submit an annotation
        """
        pass

    def test_insights_barcode_get(self) -> None:
        """Test case for insights_barcode_get

        Get all insights for a specific product, use GET /insights?barcode={barcode} instead
        """
        pass

    def test_insights_detail_id_get(self) -> None:
        """Test case for insights_detail_id_get

        Get a specific insight
        """
        pass

    def test_insights_dump_get(self) -> None:
        """Test case for insights_dump_get

        Generate a CSV dump
        """
        pass

    def test_insights_get(self) -> None:
        """Test case for insights_get

        List insights
        """
        pass

    def test_insights_random_get(self) -> None:
        """Test case for insights_random_get

        Get a random insight, use GET /insights?order_by=random instead
        """
        pass


if __name__ == '__main__':
    unittest.main()
