# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.predict_lang_product_get200_response import PredictLangProductGet200Response

class TestPredictLangProductGet200Response(unittest.TestCase):
    """PredictLangProductGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PredictLangProductGet200Response:
        """Test PredictLangProductGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PredictLangProductGet200Response`
        """
        model = PredictLangProductGet200Response()
        if include_optional:
            return PredictLangProductGet200Response(
                counts = [
                    openapi_client.models._predict_lang_product_get_200_response_counts_inner._predict_lang_product_get_200_response_counts_inner(
                        lang = 'en', 
                        count = 10, )
                    ],
                percent = [
                    openapi_client.models._predict_lang_product_get_200_response_percent_inner._predict_lang_product_get_200_response_percent_inner(
                        lang = 'en', 
                        percent = 80.5, )
                    ],
                image_ids = [
                    1
                    ]
            )
        else:
            return PredictLangProductGet200Response(
        )
        """

    def testPredictLangProductGet200Response(self):
        """Test PredictLangProductGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
