# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.questions_api import QuestionsApi


class TestQuestionsApi(unittest.TestCase):
    """QuestionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuestionsApi()

    def tearDown(self) -> None:
        pass

    def test_questions_barcode_get(self) -> None:
        """Test case for questions_barcode_get

        Get questions for a given product
        """
        pass

    def test_questions_get(self) -> None:
        """Test case for questions_get

        Fetch questions
        """
        pass

    def test_questions_popular_get(self) -> None:
        """Test case for questions_popular_get

        Get questions about popular products
        """
        pass

    def test_questions_random_get(self) -> None:
        """Test case for questions_random_get

        Get random questions
        """
        pass

    def test_questions_unanswered_get(self) -> None:
        """Test case for questions_unanswered_get

        Get unanswered question counts
        """
        pass


if __name__ == '__main__':
    unittest.main()
