# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.questions_unanswered_get200_response_questions_inner import QuestionsUnansweredGet200ResponseQuestionsInner

class TestQuestionsUnansweredGet200ResponseQuestionsInner(unittest.TestCase):
    """QuestionsUnansweredGet200ResponseQuestionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuestionsUnansweredGet200ResponseQuestionsInner:
        """Test QuestionsUnansweredGet200ResponseQuestionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuestionsUnansweredGet200ResponseQuestionsInner`
        """
        model = QuestionsUnansweredGet200ResponseQuestionsInner()
        if include_optional:
            return QuestionsUnansweredGet200ResponseQuestionsInner(
            )
        else:
            return QuestionsUnansweredGet200ResponseQuestionsInner(
        )
        """

    def testQuestionsUnansweredGet200ResponseQuestionsInner(self):
        """Test QuestionsUnansweredGet200ResponseQuestionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
