# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.insights_random_get200_response import InsightsRandomGet200Response

class TestInsightsRandomGet200Response(unittest.TestCase):
    """InsightsRandomGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsRandomGet200Response:
        """Test InsightsRandomGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsRandomGet200Response`
        """
        model = InsightsRandomGet200Response()
        if include_optional:
            return InsightsRandomGet200Response(
                insights = [
                    {"id":"3cd5aecd-edcc-4237-87d0-6595fc4e53c9","type":"label","barcode":9782012805866}
                    ]
            )
        else:
            return InsightsRandomGet200Response(
        )
        """

    def testInsightsRandomGet200Response(self):
        """Test InsightsRandomGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
