# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.questions_unanswered_get200_response import QuestionsUnansweredGet200Response

class TestQuestionsUnansweredGet200Response(unittest.TestCase):
    """QuestionsUnansweredGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuestionsUnansweredGet200Response:
        """Test QuestionsUnansweredGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuestionsUnansweredGet200Response`
        """
        model = QuestionsUnansweredGet200Response()
        if include_optional:
            return QuestionsUnansweredGet200Response(
                count = 56,
                questions = [
                    null
                    ],
                status = 'found'
            )
        else:
            return QuestionsUnansweredGet200Response(
                count = 56,
                questions = [
                    null
                    ],
                status = 'found',
        )
        """

    def testQuestionsUnansweredGet200Response(self):
        """Test QuestionsUnansweredGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
