# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.predict_category_post_request_any_of1_product import PredictCategoryPostRequestAnyOf1Product
from typing import Optional, Set
from typing_extensions import Self

class PredictCategoryPostRequestAnyOf1(BaseModel):
    """
    PredictCategoryPostRequestAnyOf1
    """ # noqa: E501
    product: PredictCategoryPostRequestAnyOf1Product
    deepest_only: Optional[StrictBool] = Field(default=None, description="If true, only return the deepest elements in the category taxonomy (don't return categories that are parents of other predicted categories) ")
    threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=0.5, description="The score above which we consider the category to be detected ")
    __properties: ClassVar[List[str]] = ["product", "deepest_only", "threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PredictCategoryPostRequestAnyOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PredictCategoryPostRequestAnyOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "product": PredictCategoryPostRequestAnyOf1Product.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "deepest_only": obj.get("deepest_only"),
            "threshold": obj.get("threshold") if obj.get("threshold") is not None else 0.5
        })
        return _obj


