# coding: utf-8

"""
    API Reference

    Robotoff provides a simple API allowing consumers to fetch predictions and annotate them.  All endpoints must be prefixed with `/api/v1`. The full URL is `https://robotoff.openfoodfacts.org/api/v1/{endpoint}`. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ServerDomainParameter(str, Enum):
    """
    The server domain associated with the image/product.  If the `server_domain` top level domain does not match the server configuration, an HTTP 400 error will be raised 
    """

    """
    allowed enum values
    """
    API_DOT_OPENFOODFACTS_DOT_ORG = 'api.openfoodfacts.org'
    API_DOT_OPENBEAUTYFACTS_DOT_ORG = 'api.openbeautyfacts.org'
    API_DOT_OPENPRODUCTFACTS_DOT_ORG = 'api.openproductfacts.org'
    API_DOT_OPENPETFOODFACTS_DOT_ORG = 'api.openpetfoodfacts.org'
    API_DOT_PRO_DOT_OPENFOODFACTS_DOT_ORG = 'api.pro.openfoodfacts.org'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServerDomainParameter from a JSON string"""
        return cls(json.loads(json_str))


